name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Run Ansible scan with minimal possible example
        uses: xlab-steampunk/spotter-action@master
        env:
          SPOTTER_USERNAME: ${{ secrets.SPOTTER_USERNAME }}
          SPOTTER_PASSWORD: ${{ secrets.SPOTTER_PASSWORD }}

      - name: Scan Ansible content with different inputs
        uses: xlab-steampunk/spotter-action@cli-dockerfile-updates
        with:
          paths: playbook.yaml
          project_id: ${{ secrets.SPOTTER_PROJECT_ID }}
          upload_values: true
          upload_metadata: true
          display_level: error
          ansible_version: 2.13
        env:
          SPOTTER_USERNAME: ${{ secrets.SPOTTER_USERNAME }}
          SPOTTER_PASSWORD: ${{ secrets.SPOTTER_PASSWORD }}
