name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Run Ansible scan with minimal possible example
        uses: xlab-steampunk/spotter-action@master
        env:
          SPOTTER_USERNAME: ${{ secrets.SPOTTER_USERNAME }}
          SPOTTER_PASSWORD: ${{ secrets.SPOTTER_PASSWORD }}
